
import java.awt.*;
import javax.swing.*;
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodos Numericos");
        setBackground(new java.awt.Color(26, 237, 26));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(215, 57, 57));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GAUSS - SEIDEL");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 23, 220));
        jLabel2.setText("X:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 75, 212));
        jLabel3.setText("Y:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(162, 54, 219));
        jLabel4.setText("Z:");

        jTextField1.setText("0");

        jTextField2.setText("0");

        jTextField3.setText("0");

        jLabel5.setForeground(new java.awt.Color(137, 18, 222));
        jLabel5.setText("X  +");

        jLabel6.setForeground(new java.awt.Color(148, 41, 225));
        jLabel6.setText("Y  +");

        jLabel7.setForeground(new java.awt.Color(148, 41, 225));
        jLabel7.setText("Z  =");

        jLabel8.setForeground(new java.awt.Color(148, 41, 225));
        jLabel8.setText("X  +");

        jLabel9.setForeground(new java.awt.Color(147, 41, 224));
        jLabel9.setText("Y  +");

        jLabel10.setForeground(new java.awt.Color(148, 41, 224));
        jLabel10.setText("Z  =");

        jLabel11.setForeground(new java.awt.Color(148, 41, 224));
        jLabel11.setText("X  +");

        jLabel12.setText("Y  +");

        jLabel13.setText("Z  =");

        jButton1.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(137, 18, 222));
        jButton1.setText("calcular");
        jButton1.setToolTipText("Comenzar Iteracion");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 249, 208)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(137, 18, 222));
        jButton2.setText("borrar");
        jButton2.setToolTipText("Limpiar Campos");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 254, 243)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(162, 54, 219));
        jLabel14.setText("Es:");

        jTextField12.setForeground(new java.awt.Color(211, 36, 36));

        jMenuBar1.setBackground(new java.awt.Color(146, 127, 219));

        jMenu2.setText("?");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q.jpg"))); // NOI18N
        jMenu3.setText("Ayuda.");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel14)
                                .addGap(3, 3, 3)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField11)
                                    .addComponent(jTextField16)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 try{
              
double uno[]=new double [4];
        double dos[]=new double [4];
        double tres[]=new double [4];
 int ban=0;
 int ban2=0;
 int ban3=0;

                      double x1,y1,z1,c1,c2,c3,es1=1,es2=1,es3=1;
            x1=Double.parseDouble(jTextField1.getText());
                        y1=Double.parseDouble(jTextField2.getText());
            z1=Double.parseDouble(jTextField3.getText());

  uno[0]=Double.parseDouble(jTextField4.getText());
  uno[1]=Double.parseDouble(jTextField5.getText());
  uno[2]=Double.parseDouble(jTextField6.getText());
  uno[3]=Double.parseDouble(jTextField7.getText());
  dos[0]=Double.parseDouble(jTextField8.getText());
  dos[1]=Double.parseDouble(jTextField9.getText());
  dos[2]=Double.parseDouble(jTextField10.getText());
  dos[3]=Double.parseDouble(jTextField11.getText());
  tres[0]=Double.parseDouble(jTextField14.getText());
  tres[1]=Double.parseDouble(jTextField13.getText());
  tres[2]=Double.parseDouble(jTextField15.getText());
  tres[3]=Double.parseDouble(jTextField16.getText());

                double ea=Double.parseDouble(jTextField12.getText());
           
                 /*JOptionPane.showMessageDialog(null,"ecuacion \n"+uno[0]+"x  "+uno[1]+"y  "+uno[2]+"z  \n"
                                                 +dos[0]+"x  "+dos[1]+"y  "+dos[2]+"z  \n"
                                                 +tres[0]+"x  "+tres[1]+"y  "+tres[2]+"z  \n");*/
        //nueve consultas con if para saber donde queda cada ecuacion para hacer su diagonal principal
     if(Math.abs(uno[0])>=Math.abs(uno[1])&&Math.abs(uno[0])>=Math.abs(uno[2]))
     {
     ban=1;
     }

           if(Math.abs(dos[0])>=Math.abs(dos[1])&&Math.abs(dos[0])>=Math.abs(dos[2]))
     {
     ban=2;
     }

           if(Math.abs(tres[0])>=Math.abs(tres[1])&&Math.abs(tres[0])>=Math.abs(tres[2]))
     {
     ban=3;
     }

           if(Math.abs(uno[1])>=Math.abs(uno[0])&&Math.abs(uno[1])>=Math.abs(uno[2]))
     {
     ban2=1;
     }

         if(Math.abs(dos[1])>=Math.abs(dos[0])&&Math.abs(dos[1])>=Math.abs(dos[2]))
     {
     ban2=2;
     }
           if(Math.abs(tres[1])>=Math.abs(tres[0])&&Math.abs(tres[1])>=Math.abs(tres[2]))
     {
     ban2=3;
     }
      //3
           if(Math.abs(uno[2])>=Math.abs(uno[0])&&Math.abs(uno[2])>=Math.abs(uno[2]))
     {
     ban3=1;
     }
        if(dos[2]>=Math.abs(dos[0])&&Math.abs(dos[2])>=Math.abs(dos[2]))
     {
     ban3=2;
     }
        if(Math.abs(tres[2])>=Math.abs(tres[0])&& Math.abs(tres[2])>=Math.abs(tres[2]))
     {
     ban3=3;
     }

        //consultas para imprimir diagonal principal

       if(ban==1)
       {
     //  System.out.println("1.- "+uno[0]+" + "+uno[1]+" + "+uno[2]);
jTextField4.setText(""+uno[0]);
jTextField5.setText(""+uno[1]);
jTextField6.setText(""+uno[2]);
jTextField7.setText(""+uno[3]);
       }
       if(ban==2)
       {
       //System.out.println("1.- "+dos[0]+" + "+dos[1]+" + "+dos[2]);
    jTextField4.setText(""+dos[0]);
jTextField5.setText(""+dos[1]);
jTextField6.setText(""+dos[2]);
jTextField7.setText(""+dos[3]);

       }
        if(ban==3)
       {
       //System.out.println("1.- "+tres[0]+" + "+tres[1]+" + "+tres[2]);
       jTextField4.setText(""+tres[0]);
jTextField5.setText(""+tres[1]);
jTextField6.setText(""+tres[2]);
jTextField7.setText(""+tres[3]);

       }
        //segunda ecuacion
        if(ban2==1)
       {
       //System.out.println("2.- "+uno[0]+" + "+uno[1]+" + "+uno[2]);
       jTextField8.setText(""+uno[0]);
       jTextField9.setText(""+uno[1]);
       jTextField10.setText(""+uno[2]);
       jTextField11.setText(""+uno[3]);

       }
       if(ban2==2)
       {
       //System.out.println("2.- "+dos[0]+" + "+dos[1]+" + "+dos[2]);
        jTextField8.setText(""+dos[0]);
       jTextField9.setText(""+dos[1]);
       jTextField10.setText(""+dos[2]);
       jTextField11.setText(""+dos[3]);

       }
        if(ban2==3)
       {
       //System.out.println("2.- "+tres[0]+" + "+tres[1]+" + "+tres[2]);
        jTextField8.setText(""+tres[0]);
       jTextField9.setText(""+tres[1]);
       jTextField10.setText(""+tres[2]);
       jTextField11.setText(""+tres[3]);

       }
        //tercera ecuacion

       if(ban3==1)
       {
       //System.out.println("3.- "+uno[0]+" + "+uno[1]+" + "+uno[2]);
        jTextField14.setText(""+uno[0]);
       jTextField13.setText(""+uno[1]);
       jTextField15.setText(""+uno[2]);
       jTextField16.setText(""+uno[3]);

       }
       if(ban3==2)
       {
       //System.out.println("3.- "+dos[0]+" + "+dos[1]+" + "+dos[2]);
        jTextField14.setText(""+dos[0]);
       jTextField13.setText(""+dos[1]);
       jTextField15.setText(""+dos[2]);
       jTextField16.setText(""+dos[3]);

       }
        if(ban3==3)
       {
       //System.out.println("3.- "+tres[0]+" + "+tres[1]+" + "+tres[2]);
        jTextField14.setText(""+tres[0]);
       jTextField13.setText(""+tres[1]);
       jTextField15.setText(""+tres[2]);
       jTextField16.setText(""+tres[3]);

       }
        //System.out.println();
       // System.out.println(" "+ban+" "+ban2+" "+ban3+"");
        Corte t=new Corte();
        double aux[]=t.calcularCorte(x1, y1, z1, uno, dos, tres, ban, ban2, ban3, ea);
   jTextField4.setForeground(new java.awt.Color(211, 36, 36));
        jTextField9.setForeground(new java.awt.Color(211, 36, 36));
        jTextField15.setForeground(new java.awt.Color(211, 36, 36));
 }          //JOptionPane.showMessageDialog(null,"resultado "+aux[0]+" "+aux[1]+" "+aux[2]);
        catch(Exception NumberFormatException)
        {
        JOptionPane.showMessageDialog(null,"Llene todos los campos para continuar" ,"Error",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        
      NewDialog b=new NewDialog(this,true);
        b.pack();
        b.setSize(517,488);
        b.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int n;
       n= JOptionPane.showConfirmDialog(null,"¿Estas seguro que quiere borrar todo?");
;
        if (n==0){
         jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField9.setForeground(new java.awt.Color(0,0, 0));
        jTextField15.setForeground(new java.awt.Color(0,0, 0));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
